# Generated by Django 2.2.6 on 2019-10-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(blank=True, max_length=10, null=True)),
                ('humidity', models.CharField(blank=True, max_length=10, null=True)),
                ('flame', models.CharField(blank=True, max_length=10, null=True)),
                ('smoke', models.CharField(blank=True, max_length=10, null=True)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
